# Generated by Django 3.0.6 on 2020-07-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
